version: '3.8'

services:
  app:
    build: 
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    environment:
      - AWS_ENV=local
      - DB_MODE=local-dynamodb
      - LOG_LEVEL=INFO
    depends_on:
      - dynamodb-local
    networks:
      - rps-network

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data"
    volumes:
      - dynamodb-data:/home/dynamodblocal/data
    networks:
      - rps-network

networks:
  rps-network:
    driver: bridge

volumes:
  dynamodb-data:
    driver: local